openapi: 3.0.0
info:
  title: Firebase REST API
  description: API for interacting with Firebase Realtime Database
  version: 1.0.0
paths:
  /api/data:
    post:
      summary: Create new data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
              required:
                - name
                - age
      responses:
        '201':
          description: Data saved successfully
        '400':
          description: Bad request - invalid data format
        '500':
          description: Internal server error

    get:
      summary: Get all data
      responses:
        '200':
          description: A list of data objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    age:
                      type: integer
        '500':
          description: Internal server error

  '/api/data/{id}':
    get:
      summary: Get data by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Data found
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  age:
                    type: integer
        '404':
          description: Data not found
        '500':
          description: Internal server error

    put:
      summary: Update data by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
              required:
                - name
                - age
      responses:
        '200':
          description: Data updated successfully
        '400':
          description: Bad request - invalid data format
        '404':
          description: Data not found
        '500':
          description: Internal server error

    delete:
      summary: Delete data by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Data deleted successfully
        '404':
          description: Data not found
        '500':
          description: Internal server error
